<script>
	import Group1 from './Group1.svelte';
	import Group2 from './Group2.svelte';
	import Group3 from './Group3.svelte';
	import Group4 from './Group4.svelte';
	import Group5 from './Group5.svelte';
	import Group6 from './Group6.svelte';
	import Group7 from './Group7.svelte';
	import Group8 from './Group8.svelte';
	import Group9 from './Group9.svelte';
	import Group10 from './Group10.svelte';
	import Group11 from './Group11.svelte';
	import Group12 from './Group12.svelte';
	import Group13 from './Group13.svelte';
	import Group14 from './Group14.svelte';
	import Group15 from './Group15.svelte';
	import Group16 from './Group16.svelte';
	import Group17 from './Group17.svelte';
	import Group18 from './Group18.svelte';
	import Group19 from './Group19.svelte';
	import Group20 from './Group20.svelte';
	import Group21 from './Group21.svelte';
	import Group22 from './Group22.svelte';
	import Group23 from './Group23.svelte';
	import Group24 from './Group24.svelte';
	import Group25 from './Group25.svelte';
	import Group26 from './Group26.svelte';
	import Group27 from './Group27.svelte';
	import Group27b from './Group27b.svelte';
	import Group28 from './Group28.svelte';
	import Group29 from './Group29.svelte';
	import Group30 from './Group30.svelte';
	import Group31 from './Group31.svelte';
	import Group32 from './Group32.svelte';
	import Group33 from './Group33.svelte';
	import Group34 from './Group34.svelte';
	import Group36 from './Group36.svelte';
	import Group37 from './Group37.svelte';
	import Group38 from './Group38.svelte';
	import Group39 from './Group39.svelte';
	import Group40 from './Group40.svelte';
	import Group41 from './Group41.svelte';
	import Group42 from './Group42.svelte';
	import Group43 from './Group43.svelte';
</script>

<!-- `<Group38/>` is paint brush with canvas. -->

<!-- <Group1 /> -->
<!-- <Group2 /> -->
<!-- <Group3 /> -->
<!-- <Group4 /> -->
<!-- <Group5 /> -->
<!-- <Group6 /> -->
<!-- <Group7 /> -->
<!-- <Group8 /> -->
<!-- <Group9 /> -->
<!-- <Group10 /> -->
<!-- <Group11 /> -->
<!-- <Group12 /> -->
<!-- <Group13 /> -->
<!-- <Group14 /> -->
<!-- <Group15 /> -->
<!-- <Group16 /> -->
<Group17 />
<!-- <Group18 /> -->
<!-- <Group19 /> -->
<!-- <Group20 /> -->
<!-- <Group21 /> -->
<!-- <Group22 /> -->
<!-- <Group23 /> -->
<!-- <Group24 /> -->
<!-- <Group25 /> -->
<!-- <Group26 /> -->
<!-- <Group27 /> -->
<!-- <Group27b /> -->
<!-- <Group28 /> -->
<!-- <Group29 /> -->
<!-- <Group30 /> -->
<!-- <Group31 /> -->
<!-- <Group32 /> -->
<!-- <Group33 /> -->
<!-- <Group34 /> -->
<!-- <Group35 /> -->
<!-- <Group36 /> -->
<!-- <Group37 /> -->
<!-- <Group38 /> -->
<!-- <Group39 /> -->
<!-- <Group40 /> -->
<!-- <Group41 /> -->
<!-- <Group41 /> -->
<!-- <Group42 /> -->
<!-- <Group43 /> -->
